apiVersion: v1
data:
  provider.yaml: |-
    - name: 'default'
      org_id: 1
      folder: ''
      type: file
      options:
        folder: /etc/grafana-dashboards
kind: ConfigMap
metadata:
  name: {{ .GrafanaProvidersConfigMapName }}
  namespace: {{ .Namespace }}
