apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  port:
    targetPort: grafana
  tls:
    termination: edge
  to:
    kind: Service
    name: grafana
  wildcardPolicy: None