apiVersion: v1
kind: Service
metadata:
  labels:
    application-monitoring: "true"
  name: grafana
spec:
  ports:
  - name: grafana
    port: 3001
    protocol: TCP
    targetPort: grafana-proxy
  selector:
    app: grafana