apiVersion: v1
kind: Service
metadata:
  labels:
    application-monitoring: "true"
  name: grafana
  namespace: {{ .Namespace }}
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: grafana-http
  selector:
    app: grafana